version: '3'

networks:
  benchmark: {}

services:

  nginx:
    image: nginx:alpine
    volumes:
    - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/conf/proxy.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
    - benchmark
    ports:
    - "8011:8001"
    - "8012:8002"
    - "8013:8003"
    - "8014:8004"
    - "8015:8005"
    - "8016:8006"
    command: nginx -g 'daemon off;'

  cruby_puma_sinatra:
    networks:
    - benchmark
    build:
      args:
        SERVER: puma
        LIBRARY: sinatra
      context: '.'
      dockerfile: Dockerfile.cruby-2.6
    ports:
    - "8001:8001"
    command: puma -p 8001 -e production

  cruby_puma_grape:
    networks:
    - benchmark
    build:
      args:
        SERVER: puma
        LIBRARY: grape
      context: '.'
      dockerfile: Dockerfile.cruby-2.6
    ports:
    - "8002:8002"
    command: puma -p 8002 -e production

  jruby_puma_sinatra:
    networks:
    - benchmark
    build:
      args:
        SERVER: puma
        LIBRARY: sinatra
      context: '.'
      dockerfile: Dockerfile.jruby-9.2
    ports:
    - "8003:8003"
    command: puma -p 8003 -e production

  jruby_puma_grape:
    networks:
    - benchmark
    build:
      args:
        SERVER: puma
        LIBRARY: grape
      context: '.'
      dockerfile: Dockerfile.jruby-9.2
    ports:
    - "8004:8004"
    command: puma -p 8004 -e production

  cruby_unicorn_sinatra:
    networks:
    - benchmark
    build:
      args:
        SERVER: unicorn
        LIBRARY: sinatra
      context: '.'
      dockerfile: Dockerfile.cruby-2.6
    ports:
    - "8005:8005"
    command: unicorn -p 8005 --env production

  cruby_unicorn_grape:
    networks:
    - benchmark
    build:
      args:
        SERVER: unicorn
        LIBRARY: grape
      context: '.'
      dockerfile: Dockerfile.cruby-2.6
    ports:
    - "8006:8006"
    command: unicorn -p 8006 --env production

  cruby_falcon_sinatra:
    networks:
    - benchmark
    build:
      args:
        SERVER: falcon
        LIBRARY: sinatra
      context: '.'
      dockerfile: Dockerfile.cruby-2.6
    ports:
    - "8007:8007"
    command: falcon -b htp://0.0.0.0:8007

  cruby_falcon_grape:
    networks:
    - benchmark
    build:
      args:
        SERVER: falcon
        LIBRARY: grape
      context: '.'
      dockerfile: Dockerfile.cruby-2.6
    ports:
    - "8008:8008"
    command: falcon -b htp://0.0.0.0:8008